---
- name: check ansible version and fail if it is not supported
  fail: msg="ansible {{ ansible_version.full}} is not supported"
  when: ansible_version.full | version_compare('1.9.1', '=')
      
- include: radiusdesk.yml
- include: freeradius.yml
- include: setupfr.yml
- include: 1.yml
- include: 2.yml
- include: 3.yml
