---
- name: install php5-fpm
  apt: name=php5-fpm state=present

- name: configure php5-fpm socket
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf
              regexp='^(listen =)'
              line='\1 /var/run/php5-fpm.sock' backrefs=yes
  notify: reload php5-fpm

- name: configure php5-fpm socket owner
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf
              regexp='^(;)(listen.owner = www-data)'
              line='\2' backrefs=yes
  notify: reload php5-fpm

- name: configure php5-fpm socket group
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf
              regexp='^(;)(listen.group = www-data)'
              line='\2' backrefs=yes
  notify: reload php5-fpm

- name: install monit
  apt: name=monit
  tags:
      - monit
  
- name: monit config for rd
  template: src=monit/rd.conf dest=/etc/monit/conf.d/rd.conf
  notify: reload monit
  tags:
      - monit

- name: modify php.ini
  lineinfile: dest=/etc/php5/fpm/php.ini
              backup=yes
              regexp='^({{ item.key }}).*'
              line='\1 = {{ item.value }}'
              backrefs=yes
  with_items:
    - { key: 'max_execution_time', value: "{{ rd_php_time_limit }}" }
    - { key: 'memory_limit',       value: '512M' }
  notify: reload php5-fpm
  tags: phptimeouts
